import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { useState } from 'react'
import Footer from '@/components/Layouts/Footer'
import Navbar from '@/components/Layouts/Navbar'
import Head from 'next/head'
// import { logIn } from '../../util/auth'
import axios from '@/lib/axios'
import { useAuth } from '@/hooks/auth'

const Social = () => {
    const router = useRouter()
    const [socialRedirectUri, setSocialRedirectUri] = useState('')
    const [callbackQuery, setCallBackQuery] = useState('')
    const [socialUser, setSocialUser] = useState('')

    const { user } = useAuth({
        middleware: 'guest',
        redirectIfAuthenticated: '/',
    })

    var {
        social,
        redirect,
        redirect_uri,
        scope,
        response_type,
        code,
        authuser,
        prompt,
    } = router.query

    useEffect(() => {
        scope = encodeURI(scope)
        if (redirect) {
            let url = ''
            url =
                redirect +
                '&redirect_uri=' +
                redirect_uri +
                '&response_type=' +
                response_type +
                '&scope=' +
                scope

            setSocialRedirectUri(url)
        } else if (code) {
            console.log('inside callback routine')
            if (social == 'google') {
                console.log('setting google callback')
                //set callback query for google signin
                let callBackQueryTemp =
                    'code=' +
                    code +
                    '&scope=' +
                    scope +
                    '&authuser=' +
                    authuser +
                    '&prompt=' +
                    prompt

                setCallBackQuery(callBackQueryTemp)

                //call callback url to backend for google and fetch user data
            } else if (social == 'facebook') {
                console.log('setting facebook callback')
                //set callback query for facebook signin
                let callBackQueryTemp = 'code=' + code
                setCallBackQuery(callBackQueryTemp)

                //call callback url to backend for facebook and fetch user data
            }
        }
    })

    /**
     * redirect to oauth client - google or facebook and get cred...
     *                          or
     *  backend callback for user's social login information
     */

    useEffect(() => {
        // console.log(callbackQuery);
        if (callbackQuery != '' && code != undefined) {
            //get user information from social provider from backend

            axios
                .get(`api/login/${social}/callback` + '?' + callbackQuery)
                .then(response => {
                    setSocialUser(response?.data || '')
                })
                .catch(error => {
                    if (error.status == 500) {
                        router.push('/join')
                    }
                })
        }
    }, [callbackQuery])

    useEffect(() => {
        if (socialRedirectUri != '' && redirect != undefined) {
            //get social redirect uri
            router.push(socialRedirectUri)
        }
    }, [socialUser, socialRedirectUri])

    return (
        <>
            <div className="min-h-screen py-0 px-2 flex flex-col justify-center ">
                <Head>
                    <title>Arpeggio</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Navbar />
                <main className="flex-1 flex flex-col justify-center items-center"></main>

                <Footer />
            </div>
        </>
    )
}

export default Social
